// DSA 100 - Hard | C++ solutions
#include <bits/stdc++.h>
using namespace std;
struct ListNode{int val;ListNode*next;ListNode(int v=0):val(v),next(nullptr){}}; struct TreeNode{int val;TreeNode*left,*right;TreeNode(int v=0):val(v),left(nullptr),right(nullptr){}};
int q71_trap(vector<int>&h){int l=0,r=h.size()-1,lm=0,rm=0,a=0;while(l<=r){if(h[l]<=h[r]){lm=max(lm,h[l]);a+=lm-h[l++];}else{rm=max(rm,h[r]);a+=rm-h[r--];}}return a;}
int q72_firstMissingPositive(vector<int>&a){int n=a.size();for(int&i:a)if(i<1||i>n)i=n+1;for(int x:a){int v=abs(x);if(v<=n&&a[v-1]>0)a[v-1]=-a[v-1];}for(int i=0;i<n;i++)if(a[i]>0)return i+1;return n+1;}
double q73_medianSortedArrays(vector<int>A,vector<int>B){if(A.size()>B.size())swap(A,B);int m=A.size(),n=B.size(),l=0,r=m;while(l<=r){int i=(l+r)/2,j=(m+n+1)/2-i,al=i?A[i-1]:INT_MIN,ar=i<m?A[i]:INT_MAX,bl=j?B[j-1]:INT_MIN,br=j<n?B[j]:INT_MAX;if(al<=br&&bl<=ar)return (m+n)%2?max(al,bl):(max(al,bl)+min(ar,br))/2.0;if(al>br)r=i-1;else l=i+1;}return 0;}
int q74_largestRectangle(vector<int>&h){h.push_back(0);vector<int>st;int ans=0;for(int i=0;i<h.size();i++){while(!st.empty()&&h[st.back()]>h[i]){int x=st.back();st.pop_back();int left=st.empty()?-1:st.back();ans=max(ans,h[x]*(i-left-1));}st.push_back(i);}h.pop_back();return ans;}
int q75_maxProduct(vector<int>&a){int mx=a[0],mn=a[0],ans=a[0];for(int i=1;i<a.size();i++){if(a[i]<0)swap(mx,mn);mx=max(a[i],mx*a[i]);mn=min(a[i],mn*a[i]);ans=max(ans,mx);}return ans;}
long long q76_countInversions(vector<int>&a){function<long long(int,int)>f=[&](int l,int r){if(r-l<2)return 0LL;int m=(l+r)/2;long long ans=f(l,m)+f(m,r);vector<int>b;b.reserve(r-l);int i=l,j=m;while(i<m||j<r){if(j==r||(i<m&&a[i]<=a[j]))b.push_back(a[i++]);else b.push_back(a[j++]),ans+=m-i;}copy(b.begin(),b.end(),a.begin()+l);return ans;};return f(0,a.size());}
string q77_minWindow(string s,string t){vector<int>c(128);for(char x:t)c[x]++;int need=t.size(),l=0,st=0,len=INT_MAX;for(int r=0;r<s.size();r++){if(c[s[r]]-->0)need--;while(!need){if(r-l+1<len)len=r-l+1,st=l;if(++c[s[l++]]>0)need++;}}return len==INT_MAX?"":s.substr(st,len);}
vector<string> q78_wordBreak(string s,vector<string>&dict){unordered_set<string>d(dict.begin(),dict.end());int n=s.size();vector<int>p(n+1,-1);p[0]=0;for(int i=0;i<n;i++)if(p[i]>=0)for(int j=i+1;j<=n;j++)if(d.count(s.substr(i,j-i)))p[j]=i;if(p[n]<0)return{};vector<string>r;for(int j=n;j;j=p[j])r.push_back(s.substr(p[j],j-p[j]));reverse(r.begin(),r.end());return r;}
bool q79_regexMatch(string s,string p){int n=s.size(),m=p.size();vector<vector<char>>d(n+1,vector<char>(m+1));d[0][0]=1;for(int j=2;j<=m;j++)if(p[j-1]=='*')d[0][j]=d[0][j-2];for(int i=1;i<=n;i++)for(int j=1;j<=m;j++)if(p[j-1]=='*')d[i][j]=d[i][j-2]||(p[j-2]=='.'||p[j-2]==s[i-1])&&d[i-1][j];else d[i][j]=(p[j-1]=='.'||p[j-1]==s[i-1])&&d[i-1][j-1];return d[n][m];}
int q80_editDistance(string a,string b){vector<int>dp(b.size()+1);iota(dp.begin(),dp.end(),0);for(int i=1;i<=a.size();i++){vector<int>ndp(b.size()+1);ndp[0]=i;for(int j=1;j<=b.size();j++)ndp[j]=min({dp[j]+1,ndp[j-1]+1,dp[j-1]+(a[i-1]!=b[j-1])});dp.swap(ndp);}return dp.back();}
int q81_longestPalSubseq(string s){int n=s.size();vector<int>dp(n);for(int i=n-1;i>=0;i--){int prev=0;dp[i]=1;for(int j=i+1;j<n;j++){int tmp=dp[j];dp[j]=s[i]==s[j]?prev+2:max(dp[j],dp[j-1]);prev=tmp;}}return n?dp[n-1]:0;}
ListNode*q82_mergeK(vector<ListNode*>&a){auto cmp=[](ListNode*x,ListNode*y){return x->val>y->val;};priority_queue<ListNode*,vector<ListNode*>,decltype(cmp)>q(cmp);for(auto*x:a)if(x)q.push(x);ListNode d;auto*t=&d;while(!q.empty()){auto*x=q.top();q.pop();t->next=x;t=x;if(x->next)q.push(x->next);}return d.next;}
ListNode*q83_reverseK(ListNode*h,int k){ListNode*p=h;for(int i=0;i<k;i++)if(!p)return h;else p=p->next;ListNode*prev=nullptr,*cur=h;for(int i=0;i<k;i++){auto*n=cur->next;cur->next=prev;prev=cur;cur=n;}h->next=q83_reverseK(cur,k);return prev;}
class q84_LRU{int cap;list<pair<int,int>>lst;unordered_map<int,list<pair<int,int>>::iterator>mp;public:q84_LRU(int c):cap(c){}int get(int k){if(!mp.count(k))return-1;auto it=mp[k];int v=it->second;lst.splice(lst.begin(),lst,it);return v;}void put(int k,int v){if(mp.count(k)){lst.splice(lst.begin(),lst,mp[k]);lst.begin()->second=v;return;}lst.push_front({k,v});mp[k]=lst.begin();if(lst.size()>cap){mp.erase(lst.back().first);lst.pop_back();}}};
class q85_MedianFinder{priority_queue<int>lo;priority_queue<int,vector<int>,greater<int>>hi;public:void addNum(int x){lo.push(x);hi.push(lo.top());lo.pop();if(hi.size()>lo.size())lo.push(hi.top()),hi.pop();}double findMedian(){return lo.size()>hi.size()?lo.top():(lo.top()+hi.top())/2.0;}};
string q86_serialize(TreeNode*r){if(!r)return"#";return to_string(r->val)+","+q86_serialize(r->left)+","+q86_serialize(r->right);}TreeNode*q86_deserialize(string s){stringstream ss(s);string x;vector<string>a;while(getline(ss,x,','))a.push_back(x);int i=0;function<TreeNode*()>f=[&]() -> TreeNode* {if(i>=a.size()||a[i]=="#"){if(i<a.size())++i;return nullptr;}auto*r=new TreeNode(stoi(a[i++]));r->left=f();r->right=f();return r;};return f();}
int q87_maxPathSum(TreeNode*r){int ans=INT_MIN;function<int(TreeNode*)>f=[&](TreeNode*x){if(!x)return 0;int l=max(0,f(x->left)),rr=max(0,f(x->right));ans=max(ans,x->val+l+rr);return x->val+max(l,rr);};f(r);return ans;}
void q88_recoverBST(TreeNode*r){TreeNode*first=nullptr,*second=nullptr,*prev=nullptr;stack<TreeNode*>st;while(r||!st.empty()){while(r)st.push(r),r=r->left;r=st.top();st.pop();if(prev&&prev->val>r->val){if(!first)first=prev;second=r;}prev=r;r=r->right;}swap(first->val,second->val);}
struct Trie{bool end=false;array<Trie*,26>c{};};class q89_Trie{Trie*root=new Trie;public:void insert(string&s){auto*p=root;for(char x:s){int i=x-'a';if(!p->c[i])p->c[i]=new Trie;p=p->c[i];}p->end=true;}bool search(string&s){auto*p=root;for(char x:s){p=p->c[x-'a'];if(!p)return false;}return p->end;}bool startsWith(string&s){auto*p=root;for(char x:s){p=p->c[x-'a'];if(!p)return false;}return true;}};
vector<string> q90_wordSearchII(vector<vector<char>>&b,vector<string>&words){struct N{string w;N*c[26]{};};N*root=new N;for(auto&w:words){auto*p=root;for(char ch:w){int i=ch-'a';if(!p->c[i])p->c[i]=new N;p=p->c[i];}p->w=w;}set<string>ans;int n=b.size(),m=b[0].size();function<void(int,int,N*)>dfs=[&](int x,int y,N*p){char ch=b[x][y];if(ch=='#'||!p->c[ch-'a'])return;p=p->c[ch-'a'];if(!p->w.empty())ans.insert(p->w);b[x][y]='#';for(auto[dx,dy]:vector<pair<int,int>>{{1,0},{-1,0},{0,1},{0,-1}}){int a=x+dx,c=y+dy;if(a>=0&&a<n&&c>=0&&c<m)dfs(a,c,p);}b[x][y]=ch;};for(int i=0;i<n;i++)for(int j=0;j<m;j++)dfs(i,j,root);return vector<string>(ans.begin(),ans.end());}
vector<long long> q91_dijkstra(int n,vector<vector<pair<int,int>>>&g,int src){const long long INF=4e18;vector<long long>d(n,INF);priority_queue<pair<long long,int>,vector<pair<long long,int>>,greater<pair<long long,int>>>q;d[src]=0;q.push({0,src});while(!q.empty()){auto[du,u]=q.top();q.pop();if(du!=d[u])continue;for(auto[v,w]:g[u])if(d[v]>du+w)d[v]=du+w,q.push({d[v],v});}return d;}
int q92_networkDelay(int n,vector<vector<int>>&e,int s){vector<vector<pair<int,int>>>g(n);for(auto&x:e)g[x[0]-1].push_back({x[1]-1,x[2]});auto d=q91_dijkstra(n,g,s-1);long long mx=*max_element(d.begin(),d.end());return mx>=4e18?-1:mx;}
struct DSU{vector<int>p,r;DSU(int n):p(n),r(n,0){iota(p.begin(),p.end(),0);}int f(int x){return p[x]==x?x:p[x]=f(p[x]);}bool u(int a,int b){a=f(a);b=f(b);if(a==b)return false;if(r[a]<r[b])swap(a,b);p[b]=a;if(r[a]==r[b])r[a]++;return true;}};
int q93_mst(int n,vector<vector<int>>&e){sort(e.begin(),e.end(),[](auto&a,auto&b){return a[2]<b[2];});DSU d(n);int ans=0;for(auto&x:e)if(d.u(x[0],x[1]))ans+=x[2];return ans;}
vector<vector<int>> q94_criticalConnections(int n,vector<vector<int>>&e){vector<vector<int>>g(n);for(int i=0;i<e.size();i++)g[e[i][0]].push_back(i),g[e[i][1]].push_back(i);vector<int>tin(n,-1),low(n);vector<vector<int>>ans;int timer=0;function<void(int,int)>dfs=[&](int u,int pe){tin[u]=low[u]=timer++;for(int id:g[u])if(id!=pe){int v=e[id][0]^e[id][1]^u;if(tin[v]>=0)low[u]=min(low[u],tin[v]);else dfs(v,id),low[u]=min(low[u],low[v]),(void)(low[v]>tin[u]&&(ans.push_back({u,v}),0));}};dfs(0,-1);return ans;}
vector<int> q95_scc(int n,vector<vector<int>>&e){vector<vector<int>>g(n),rg(n);for(auto&x:e)g[x[0]].push_back(x[1]),rg[x[1]].push_back(x[0]);vector<int>vis(n),ord,comp(n,-1);function<void(int)>f=[&](int u){vis[u]=1;for(int v:g[u])if(!vis[v])f(v);ord.push_back(u);};for(int i=0;i<n;i++)if(!vis[i])f(i);function<void(int,int)>r=[&](int u,int c){comp[u]=c;for(int v:rg[u])if(comp[v]<0)r(v,c);};reverse(ord.begin(),ord.end());int c=0;for(int u:ord)if(comp[u]<0)r(u,c++);return comp;}
string q96_alienDictionary(vector<string>&w){map<char,set<char>>g;map<char,int>d;for(auto&s:w)for(char c:s)d[c]=0;for(int i=1;i<w.size();i++){string&a=w[i-1],&b=w[i];int k=0;while(k<a.size()&&k<b.size()&&a[k]==b[k])k++;if(k==b.size()&&k<a.size())return"";if(k<a.size()&&k<b.size()&&g[a[k]].insert(b[k]).second)d[b[k]]++;}queue<char>q;for(auto [c,x]:d)if(!x)q.push(c);string r;while(!q.empty()){char c=q.front();q.pop();r+=c;for(char v:g[c])if(!--d[v])q.push(v);}return r.size()==d.size()?r:"";}
bool q97_partitionEqual(vector<int>&a){int sum=accumulate(a.begin(),a.end(),0);if(sum%2)return false;int t=sum/2;vector<char>dp(t+1);dp[0]=1;for(int x:a)for(int s=t;s>=x;s--)dp[s]|=dp[s-x];return dp[t];}
int q98_minCut(string s){int n=s.size();vector<int>cut(n+1);iota(cut.begin(),cut.end(),-1);for(int i=0;i<n;i++)for(int l=i,r=i;l>=0&&r<n&&s[l]==s[r];l--,r++)cut[r+1]=min(cut[r+1],cut[l]+1);for(int i=0;i<n-1;i++)for(int l=i,r=i+1;l>=0&&r<n&&s[l]==s[r];l--,r++)cut[r+1]=min(cut[r+1],cut[l]+1);return cut[n];}
long long q99_nQueens(int n){long long ans=0;function<void(int,int,int,int)>dfs=[&](int r,int c,int d1,int d2){if(r==n){ans++;return;}int avail=((1<<n)-1)&~(c|d1|d2);while(avail){int b=avail&-avail;avail-=b;dfs(r+1,c|b,(d1|b)<<1,(d2|b)>>1);}};dfs(0,0,0,0);return ans;}
int q100_burstBalloons(vector<int>a){a.insert(a.begin(),1);a.push_back(1);int n=a.size();vector<vector<int>>dp(n,vector<int>(n));for(int len=2;len<n;len++)for(int l=0;l+len<n;l++){int r=l+len;for(int k=l+1;k<r;k++)dp[l][r]=max(dp[l][r],dp[l][k]+a[l]*a[k]*a[r]+dp[k][r]);}return dp[0][n-1];}
