// DSA 100 - Medium | C++ solutions
#include <bits/stdc++.h>
using namespace std; struct ListNode{int val;ListNode*next;ListNode(int v=0):val(v),next(nullptr){}}; struct TreeNode{int val;TreeNode*left,*right;TreeNode(int v=0):val(v),left(nullptr),right(nullptr){}};
int q31_longestConsecutive(vector<int>&a){unordered_set<int>s(a.begin(),a.end());int ans=0;for(int x:a)if(!s.count(x-1)){int y=x;while(s.count(y))y++;ans=max(ans,y-x);}return ans;}
vector<int> q32_productExceptSelf(vector<int>&a){int n=a.size();vector<int>r(n,1);for(int i=1;i<n;i++)r[i]=r[i-1]*a[i-1];int p=1;for(int i=n-1;i>=0;i--){r[i]*=p;p*=a[i];}return r;}
int q33_subarraySum(vector<int>&a,int k){unordered_map<int,int>m{{0,1}};int sum=0,ans=0;for(int x:a){sum+=x;ans+=m[sum-k];m[sum]++;}return ans;}
vector<int> q34_topKFrequent(vector<int>&a,int k){unordered_map<int,int>f;for(int x:a)f[x]++;vector<vector<int>>b(a.size()+1);for(auto [x,c]:f)b[c].push_back(x);vector<int>r;for(int c=a.size();c&&r.size()<k;c--)for(int x:b[c]){r.push_back(x);if(r.size()==k)break;}return r;}
void q35_rotateArray(vector<int>&a,int k){if(a.empty())return;k%=a.size();reverse(a.begin(),a.end());reverse(a.begin(),a.begin()+k);reverse(a.begin()+k,a.end());}
vector<int> q36_spiralMatrix(vector<vector<int>>&a){vector<int>r;if(a.empty())return r;int t=0,b=a.size()-1,l=0,rr=a[0].size()-1;while(t<=b&&l<=rr){for(int j=l;j<=rr;j++)r.push_back(a[t][j]);t++;for(int i=t;i<=b;i++)r.push_back(a[i][rr]);rr--;if(t<=b)for(int j=rr;j>=l;j--)r.push_back(a[b][j]);b--;if(l<=rr)for(int i=b;i>=t;i--)r.push_back(a[i][l]);l++;}return r;}
vector<vector<int>> q37_mergeIntervals(vector<vector<int>>a){sort(a.begin(),a.end());vector<vector<int>>r;for(auto v:a)if(r.empty()||r.back()[1]<v[0])r.push_back(v);else r.back()[1]=max(r.back()[1],v[1]);return r;}
vector<vector<int>> q38_insertInterval(vector<vector<int>>a,vector<int>n){vector<vector<int>>r;int i=0;while(i<a.size()&&a[i][1]<n[0])r.push_back(a[i++]);while(i<a.size()&&a[i][0]<=n[1])n={min(n[0],a[i][0]),max(n[1],a[i][1])},i++;r.push_back(n);while(i<a.size())r.push_back(a[i++]);return r;}
int q39_longestUnique(string s){vector<int>last(256,-1);int l=0,ans=0;for(int i=0;i<s.size();i++){l=max(l,last[(unsigned char)s[i]]+1);last[(unsigned char)s[i]]=i;ans=max(ans,i-l+1);}return ans;}
int q40_characterReplacement(string s,int k){vector<int>c(26);int l=0,mx=0,ans=0;for(int r=0;r<s.size();r++){mx=max(mx,++c[s[r]-'A']);while(r-l+1-mx>k)c[s[l++]-'A']--;ans=max(ans,r-l+1);}return ans;}
bool q41_permutationInString(string p,string s){if(p.size()>s.size())return false;vector<int>a(26),b(26);for(char c:p)a[c-'a']++;for(int i=0;i<s.size();i++){b[s[i]-'a']++;if(i>=p.size())b[s[i-p.size()]-'a']--;if(a==b)return true;}return false;}
string q42_minWindow(string s,string t){vector<int>c(128);for(char x:t)c[x]++;int need=t.size(),l=0,st=0,len=INT_MAX;for(int r=0;r<s.size();r++){if(c[s[r]]-->0)need--;while(!need){if(r-l+1<len)st=l,len=r-l+1;if(++c[s[l++]]>0)need++;}}return len==INT_MAX?"":s.substr(st,len);}
vector<vector<string>> q43_groupShifted(vector<string>&a){unordered_map<string,vector<string>>m;for(auto&s:a){string k;if(s.size()==1)k="";else for(int i=1;i<s.size();i++)k+=char('a'+(s[i]-s[i-1]+26)%26)+',';m[k].push_back(s);}vector<vector<string>>r;for(auto&[k,v]:m)r.push_back(v);return r;}
vector<vector<int>> q44_threeSum(vector<int>&a){sort(a.begin(),a.end());vector<vector<int>>r;for(int i=0;i<a.size();i++){if(i&&a[i]==a[i-1])continue;int l=i+1,j=a.size()-1;while(l<j){long x=(long)a[i]+a[l]+a[j];if(x==0){r.push_back({a[i],a[l],a[j]});while(l<j&&a[l]==a[l+1])l++;while(l<j&&a[j]==a[j-1])j--;l++;j--;}else if(x<0)l++;else j--;}}return r;}
int q45_maxArea(vector<int>&a){int l=0,r=a.size()-1,ans=0;while(l<r){ans=max(ans,min(a[l],a[r])*(r-l));if(a[l]<a[r])l++;else r--;}return ans;}
void q46_sortColors(vector<int>&a){int l=0,m=0,r=a.size()-1;while(m<=r){if(a[m]==0)swap(a[l++],a[m++]);else if(a[m]==1)m++;else swap(a[m],a[r--]);}}
int q47_kthLargest(vector<int>a,int k){nth_element(a.begin(),a.end()-k,a.end());return a[a.size()-k];}
ListNode*q48_removeNth(ListNode*h,int n){ListNode d(0);d.next=h;auto*f=&d,*s=&d;for(int i=0;i<n;i++)f=f->next;while(f->next)f=f->next,s=s->next;s->next=s->next->next;return d.next;}
ListNode*q49_addTwoNumbers(ListNode*a,ListNode*b){ListNode d,*t=&d;int c=0;while(a||b||c){int x=(a?a->val:0)+(b?b->val:0)+c;c=x/10;t->next=new ListNode(x%10);t=t->next;if(a)a=a->next;if(b)b=b->next;}return d.next;}
void q50_reorderList(ListNode*h){if(!h||!h->next)return;auto s=h,f=h;while(f->next&&f->next->next)s=s->next,f=f->next->next;auto p=s->next;s->next=nullptr;ListNode*rev=nullptr;while(p){auto n=p->next;p->next=rev;rev=p;p=n;}auto a=h,b=rev;while(b){auto an=a->next,bn=b->next;a->next=b;b->next=an;a=an;b=bn;}}
ListNode*q51_intersection(ListNode*a,ListNode*b){auto*p=a,*q=b;while(p!=q)p=p?p->next:b,q=q?q->next:a;return p;}
/* Q52: node has next + random. */
struct RNode{int val;RNode*next;RNode*random;}; RNode*q52_copyRandom(RNode*h){unordered_map<RNode*,RNode*>m;for(auto*p=h;p;p=p->next)m[p]=new RNode{p->val,nullptr,nullptr};for(auto*p=h;p;p=p->next)m[p]->next=m[p->next],m[p]->random=m[p->random];return h?m[h]:nullptr;}
vector<int> q53_dailyTemperatures(vector<int>&a){vector<int>r(a.size()),st;for(int i=0;i<a.size();i++){while(!st.empty()&&a[i]>a[st.back()])r[st.back()]=i-st.back(),st.pop_back();st.push_back(i);}return r;}
int q54_evalRPN(vector<string>&t){stack<long long>s;for(auto&x:t){if(x.size()==1&&string("+-*/").find(x[0])!=string::npos){auto b=s.top();s.pop();auto a=s.top();s.pop();if(x[0]=='+')s.push(a+b);else if(x[0]=='-')s.push(a-b);else if(x[0]=='*')s.push(a*b);else s.push(a/b);}else s.push(stoll(x));}return s.top();}
class q55_MinStack{stack<pair<int,int>>s;public:void push(int x){s.push({x,s.empty()?x:min(x,s.top().second)});}void pop(){s.pop();}int top(){return s.top().first;}int getMin(){return s.top().second;}};
vector<int> q56_slidingMaximum(vector<int>&a,int k){deque<int>q;vector<int>r;for(int i=0;i<a.size();i++){while(!q.empty()&&q.front()<=i-k)q.pop_front();while(!q.empty()&&a[q.back()]<=a[i])q.pop_back();q.push_back(i);if(i>=k-1)r.push_back(a[q.front()]);}return r;}
vector<vector<int>> q57_kClosest(vector<vector<int>>&p,int k){nth_element(p.begin(),p.begin()+k,p.end(),[](auto&a,auto&b){return a[0]*a[0]+a[1]*a[1]<b[0]*b[0]+b[1]*b[1];});p.resize(k);return p;}
int q58_taskScheduler(vector<char>&t,int n){vector<int>c(26);for(char x:t)c[x-'A']++;int mx=*max_element(c.begin(),c.end()),cnt=count(c.begin(),c.end(),mx);return max((int)t.size(),(mx-1)*(n+1)+cnt);}
bool q59_validateBST(TreeNode*r){function<bool(TreeNode*,long long,long long)>f=[&](TreeNode*x,long long l,long long h){return!x||(l<x->val&&x->val<h&&f(x->left,l,x->val)&&f(x->right,x->val,h));};return f(r,LLONG_MIN,LLONG_MAX);}
TreeNode*q60_lcaBST(TreeNode*r,TreeNode*a,TreeNode*b){while(r){if(a->val<r->val&&b->val<r->val)r=r->left;else if(a->val>r->val&&b->val>r->val)r=r->right;else return r;}return nullptr;}
vector<int> q61_rightView(TreeNode*r){vector<int>res;if(!r)return res;queue<TreeNode*>q{{r}};while(!q.empty()){int n=q.size();while(n--){auto*x=q.front();q.pop();if(n==0)res.push_back(x->val);if(x->left)q.push(x->left);if(x->right)q.push(x->right);}}return res;}
TreeNode*q62_buildTree(vector<int>&pre,vector<int>&in){unordered_map<int,int>mp;for(int i=0;i<in.size();i++)mp[in[i]]=i;int pi=0;function<TreeNode*(int,int)>f=[&](int l,int r){if(l>r)return(TreeNode*)nullptr;int v=pre[pi++],m=mp[v];auto*x=new TreeNode(v);x->left=f(l,m-1);x->right=f(m+1,r);return x;};return f(0,in.size()-1);}
int q63_diameter(TreeNode*r){int ans=0;function<int(TreeNode*)>f=[&](TreeNode*x){if(!x)return 0;int l=f(x->left),rr=f(x->right);ans=max(ans,l+rr);return 1+max(l,rr);};f(r);return ans;}
int q64_kthSmallest(TreeNode*r,int k){stack<TreeNode*>s;while(1){while(r)s.push(r),r=r->left;r=s.top();s.pop();if(--k==0)return r->val;r=r->right;}}
int q65_numIslands(vector<vector<char>>&g){int n=g.size(),m=n?g[0].size():0,ans=0;for(int i=0;i<n;i++)for(int j=0;j<m;j++)if(g[i][j]=='1'){ans++;queue<pair<int,int>>q; q.push({i,j});g[i][j]='0';while(!q.empty()){auto [x,y]=q.front();q.pop();for(auto [dx,dy]:vector<pair<int,int>>{{1,0},{-1,0},{0,1},{0,-1}}){int a=x+dx,b=y+dy;if(a>=0&&a<n&&b>=0&&b<m&&g[a][b]=='1')g[a][b]='0',q.push({a,b});}}}return ans;}
// Q66 Clone Graph: Node definition assumed as {int val; vector<Node*> neighbors;};
struct GNode{int val;vector<GNode*>neighbors;}; GNode*q66_cloneGraph(GNode*n){if(!n)return nullptr;unordered_map<GNode*,GNode*>mp;queue<GNode*>q;mp[n]=new GNode{n->val,{}};q.push(n);while(!q.empty()){auto*x=q.front();q.pop();for(auto*y:x->neighbors){if(!mp.count(y))mp[y]=new GNode{y->val,{}},q.push(y);mp[x]->neighbors.push_back(mp[y]);}}return mp[n];}
bool q67_courseSchedule(int n,vector<vector<int>>&pre){vector<vector<int>>g(n);vector<int>d(n);for(auto&p:pre)g[p[1]].push_back(p[0]),d[p[0]]++;queue<int>q;for(int i=0;i<n;i++)if(!d[i])q.push(i);int c=0;while(!q.empty()){int u=q.front();q.pop();c++;for(int v:g[u])if(!--d[v])q.push(v);}return c==n;}
int q68_shortestPath(int n,vector<vector<int>>&edges,int s,int t){vector<vector<int>>g(n);for(auto&e:edges)g[e[0]].push_back(e[1]),g[e[1]].push_back(e[0]);vector<int>d(n,-1);queue<int>q;q.push(s);d[s]=0;while(!q.empty()){int u=q.front();q.pop();for(int v:g[u])if(d[v]<0)d[v]=d[u]+1,q.push(v);}return d[t];}
int q69_rottingOranges(vector<vector<int>>&g){queue<pair<int,int>>q;int fresh=0,time=0;for(int i=0;i<g.size();i++)for(int j=0;j<g[0].size();j++)if(g[i][j]==2)q.push({i,j});else if(g[i][j]==1)fresh++;while(!q.empty()&&fresh){int n=q.size();while(n--){auto[x,y]=q.front();q.pop();for(auto[dx,dy]:vector<pair<int,int>>{{1,0},{-1,0},{0,1},{0,-1}}){int a=x+dx,b=y+dy;if(a>=0&&a<g.size()&&b>=0&&b<g[0].size()&&g[a][b]==1)g[a][b]=2,fresh--,q.push({a,b});}}time++;}return fresh?-1:time;}
vector<vector<int>> q70_pacificAtlantic(vector<vector<int>>&h){int n=h.size(),m=n?h[0].size():0;vector<vector<int>>A(n,vector<int>(m)),B=A;function<void(int,int,vector<vector<int>>&)>dfs=[&](int x,int y,auto&v){if(v[x][y])return;v[x][y]=1;for(auto[dx,dy]:vector<pair<int,int>>{{1,0},{-1,0},{0,1},{0,-1}}){int a=x+dx,b=y+dy;if(a>=0&&a<n&&b>=0&&b<m&&h[a][b]>=h[x][y])dfs(a,b,v);}};for(int i=0;i<n;i++)dfs(i,0,A),dfs(i,m-1,B);for(int j=0;j<m;j++)dfs(0,j,A),dfs(n-1,j,B);vector<vector<int>>r;for(int i=0;i<n;i++)for(int j=0;j<m;j++)if(A[i][j]&&B[i][j])r.push_back({i,j});return r;}
